services:

  db:
    image: postgres:15.0-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  web:
    build: .
    restart: always
    depends_on: 
      - db
    volumes:
      - static_value:/app/staticfiles/
    env_file:
      - ./.env

  nginx:
    image: nginx:1.21.3-alpine
    restart: always
    depends_on:
      - web 
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/staticfiles/

volumes:
  postgres_data: 
  static_value:  
