# Generated by Django 5.0.2 on 2024-03-01 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stripe_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('item_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='stripe_app.item')),
            ],
            options={
                'ordering': ['item_id__name'],
            },
        ),
    ]
